# Generated by Django 6.0 on 2025-12-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('city', models.CharField(default='', max_length=255, verbose_name='城市名')),
                ('url', models.CharField(default='', max_length=255, verbose_name='城市参数')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Part1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastHeight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mastSmall', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'part1',
            },
        ),
        migrations.CreateModel(
            name='Part2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('averageHeight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('averageSmall', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'part2',
            },
        ),
        migrations.CreateModel(
            name='Part3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastAir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lostAir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'part3',
            },
        ),
        migrations.CreateModel(
            name='Part4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('averageAir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'part4',
            },
        ),
        migrations.CreateModel(
            name='Part5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windOrder', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'part5',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('averageHeight', models.CharField(default='', max_length=255, verbose_name='月平均高温')),
                ('averageSmall', models.CharField(default='', max_length=255, verbose_name='月平均低温')),
                ('mastHeight', models.CharField(default='', max_length=255, verbose_name='月最低高温')),
                ('mastSmall', models.CharField(default='', max_length=255, verbose_name='月最高低温')),
                ('averageAir', models.CharField(default='', max_length=255, verbose_name='平均空气质量')),
                ('mastAir', models.CharField(default='', max_length=255, verbose_name='最高空气质量')),
                ('lostAir', models.CharField(default='', max_length=255, verbose_name='最低空气质量')),
                ('date', models.CharField(default='', max_length=255, verbose_name='日期')),
                ('weekDay', models.CharField(default='', max_length=255, verbose_name='星期')),
                ('mastHeightDay', models.CharField(default='', max_length=255, verbose_name='日高温')),
                ('mastSmallDay', models.CharField(default='', max_length=255, verbose_name='日低温')),
                ('wearther', models.CharField(default='', max_length=255, verbose_name='天气')),
                ('wind', models.CharField(default='', max_length=255, verbose_name='风向')),
                ('windOrder', models.CharField(default='', max_length=255, verbose_name='风力')),
                ('city', models.CharField(default='', max_length=255, verbose_name='城市')),
            ],
            options={
                'db_table': 'weatherinfo',
            },
        ),
    ]
